#include <string>
#include <vector>
#include <iostream>
#include "read_data.h"
//This utility reads trajectory data from csv file generated by the network model and writes pactor to the database table Link_Probability


int main(int argc, char* argv[])
{
	using namespace std;
	int res;
	cout << "Running main() from LinkProbability.cpp\n";
	//create an empty database
	if (argc == 2)
	{
		string db_prefix = argv[1];
		unique_ptr<odb::database> db = create_sqlite_database(db_prefix);
		cout << "Crated and empty database in " << db_prefix << "\n";
		return 0;
	}
	if (argc < 2) 
	{
		std::cout << "Usage: " << argv[0] << " <db_prefix> [trajectory_file]\n";
		return 1;
	}
	string db_prefix = argv[1];
	string trajectory_fn = argv[2];
	polaris::Matrix mat;
	cout << "Reading data from file " << trajectory_fn << "\n";
	res = ReadFromFile(trajectory_fn, mat);
	std::cout << "Number of rows in the matrix: " << mat.M().size() << "\n";
	if (res == 0)
	{
		cout << "Dumping results to the database " << db_prefix << "\n";
		return DumpToDb(db_prefix, mat);
	}
	else
		return res;
}