#! /bin/bash

source_dir=$1
target_scenario=$2
path_dir=$PWD

if [ -d "workspaces/$target_scenario" ]; then
    echo rm -rf workspaces/$target_scenario
    rm -rf workspaces/$target_scenario
fi

mkdir workspaces/$target_scenario
chmod +x common/deljobs common/display common/monitor common/plot_all common/plot_*
chmod +x plot_*
cp -rf common workspaces/$target_scenario/bin
mkdir workspaces/$target_scenario/results
mkdir workspaces/$target_scenario/scenarios

cd workspaces/$target_scenario/bin
echo $path_dir
echo python weather_prepare.py $source_dir $path_dir/workspaces/$target_scenario/scenarios
python weather_prepare.py $source_dir $path_dir/workspaces/$target_scenario/scenarios
echo python weather_submit.py $path_dir/workspaces/$target_scenario/scenarios
python weather_submit.py $path_dir/workspaces/$target_scenario/scenarios
./monitor 
