#!/bin/bash
target_dir=../scenarios
data_dir=../results
scenarios=`ls ${target_dir}` 
for scenario in $scenarios
do
    tail -n +2 ${target_dir}/${scenario}/moe_network.csv | awk -f hourly_demand_arrival.awk > $data_dir/${scenario}_hourly_demand_arrival.csv
done

awk -f hourly_demand_arrival.awk ${data_dir}/combined_moe_network.csv > $data_dir/combined_hourly_demand_arrival.csv

# plot hourly demand
dirs=`ls ${target_dir}`
i=1
for dir in $dirs
do
    scenarios[$i]=$dir
    let i=i+1
done
let num_scenarios=i-1
cp /dev/null plt.tmp
echo set term png size 768,480 >> plt.tmp
echo set xlabel \"Time\" >> plt.tmp
echo set ylabel \"Number of vehicles\" >> plt.tmp
echo set output \"hourly_demand.png\" >> plt.tmp
echo set title \"Time dependent hourly demand pattern of Chicago network for various weather scenarios\" >> plt.tmp
echo set xdata time >> plt.tmp
echo set datafile separator \",\" >> plt.tmp
echo set timefmt \"%H:%M:%S\" >> plt.tmp
echo set xtics \(\"00:00\" \"00:00\", \"02:00\" \"02:00\", \"04:00\" \"04:00\", \"06:00\" \"06:00\", \"08:00\" \"08:00\", \"10:00\" \"10:00\", \"12:00\" \"12:00\", \"14:00\" \"14:00\", \"16:00\" \"16:00\", \"18:00\" \"18:00\", \"20:00\" \"20:00\", \"22:00\" \"22:00\", \"24:00\" \"24:00\"\) >> plt.tmp
echo set key left top >> plt.tmp
i=1
for dir in $dirs
do
    if [ $i == 1 ] 
    then 
        echo plot \[\"00:00:00\":\"24:00:00\"\]\[0:\] \'$data_dir/${scenarios[$i]}_hourly_demand_arrival.csv\' using 1:2 title \'${scenarios[$i]}\' with steps $i, \\ >> plt.tmp
    else
        echo \'$data_dir/${scenarios[$i]}_hourly_demand_arrival.csv\' using 1:2 title \'${scenarios[$i]}\' with steps $i, \\ >> plt.tmp
    fi
    let i=i+1
done
echo \'$data_dir/combined_hourly_demand_arrival.csv\' using 1:2 title \'WAVG\' with steps $i >> plt.tmp
gnuplot plt.tmp
rm plt.tmp

# plot hourly arrival
cp /dev/null plt.tmp
echo set term png size 768,480 >> plt.tmp
echo set xlabel \"Time\" >> plt.tmp
echo set ylabel \"Number of vehicles\" >> plt.tmp
echo set output \"hourly_arrival.png\" >> plt.tmp
echo set title \"Time dependent hourly arrival pattern of Chicago network for various weather scenarios\" >> plt.tmp
echo set xdata time >> plt.tmp
echo set datafile separator \",\" >> plt.tmp
echo set timefmt \"%H:%M:%S\" >> plt.tmp
echo set xtics \(\"00:00\" \"00:00\", \"02:00\" \"02:00\", \"04:00\" \"04:00\", \"06:00\" \"06:00\", \"08:00\" \"08:00\", \"10:00\" \"10:00\", \"12:00\" \"12:00\", \"14:00\" \"14:00\", \"16:00\" \"16:00\", \"18:00\" \"18:00\", \"20:00\" \"20:00\", \"22:00\" \"22:00\", \"24:00\" \"24:00\"\) >> plt.tmp
echo set key left top >> plt.tmp
i=1
for dir in $dirs
do
    if [ $i == 1 ] 
    then 
        echo plot \[\"00:00:00\":\"24:00:00\"\]\[0:\] \'$data_dir/${scenarios[$i]}_hourly_demand_arrival.csv\' using 1:3 title \'${scenarios[$i]}\' with steps $i, \\ >> plt.tmp
    else
        echo \'$data_dir/${scenarios[$i]}_hourly_demand_arrival.csv\' using 1:3 title \'${scenarios[$i]}\' with steps $i, \\ >> plt.tmp
    fi
    let i=i+1
done
echo \'$data_dir/combined_hourly_demand_arrival.csv\' using 1:3 title \'WAVG\' with steps $i >> plt.tmp
gnuplot plt.tmp
rm plt.tmp
