#! /bin/bash
target_dir=../scenarios
data_dir=../results
dirs=`ls ${target_dir}`
i=1
for dir in $dirs
do
    scenarios[$i]=$dir
    let i=i+1
done
let num_scenarios=i-1
cp /dev/null plt.tmp

echo set term unknown >> plt.tmp
echo set xlabel \"Time\" >> plt.tmp
echo set ylabel \"Average Link Speed \(MPH\)\" >> plt.tmp
echo set title \"Average link speed of Chicago network for various weather scenarios\" >> plt.tmp
echo set xdata time >> plt.tmp
echo set datafile separator \",\" >> plt.tmp
echo set timefmt \"%H:%M:%S\" >> plt.tmp
echo set xtics \(\"00:00\" \"00:00\", \"02:00\" \"02:00\", \"04:00\" \"04:00\", \"06:00\" \"06:00\", \"08:00\" \"08:00\", \"10:00\" \"10:00\", \"12:00\" \"12:00\", \"14:00\" \"14:00\", \"16:00\" \"16:00\", \"18:00\" \"18:00\", \"20:00\" \"20:00\", \"22:00\" \"22:00\", \"24:00\" \"24:00\"\) >> plt.tmp
echo set key outside >> plt.tmp
echo set key right top >> plt.tmp
i=1
for dir in $dirs
do
    if [ $i == 1 ] 
    then 
        echo plot \[\"00:00:00\":\"24:00:00\"\]\[:\] \'${target_dir}/${scenarios[$i]}/moe_network.csv\' every ::2 using 1:7 title \'${scenarios[$i]}\' with line $i, \\ >> plt.tmp
    else
        echo \'${target_dir}/${scenarios[$i]}/moe_network.csv\' every ::2 using 1:7 title \'${scenarios[$i]}\' with line $i, \\ >> plt.tmp
    fi
    let i=i+1
done
echo \'$data_dir/combined_moe_network.csv\' every ::2 using 1:7 title \'WAVG\' with line $i >> plt.tmp

echo set yr \[GPVAL_DATA_Y_MIN:GPVAL_DATA_Y_MAX\] >> plt.tmp

#echo lower_bound = \(GPVAL_DATA_Y_MIN - 5 \< 0\)\?0\:\(GPVAL_DATA_Y_MIN - 5\) >> plt.tmp
echo lower_bound = GPVAL_DATA_Y_MIN >> plt.tmp

echo set term png size 768,480 >> plt.tmp
echo set output \"speed.png\" >> plt.tmp
i=1
for dir in $dirs
do
    if [ $i == 1 ] 
    then 
        echo plot \[\"00:00:00\":\"24:00:00\"\]\[lower_bound:\] \'${target_dir}/${scenarios[$i]}/moe_network.csv\' every ::2 using 1:7 title \'${scenarios[$i]}\' with line $i, \\ >> plt.tmp
    else
        echo \'${target_dir}/${scenarios[$i]}/moe_network.csv\' every ::2 using 1:7 title \'${scenarios[$i]}\' with line $i, \\ >> plt.tmp
    fi
    let i=i+1
done
echo \'$data_dir/combined_moe_network.csv\' every ::2 using 1:7 title \'WAVG\' with line $i >> plt.tmp

gnuplot plt.tmp
rm plt.tmp
