#!/bin/bash
target_dir=../scenarios
dirs=`ls ${target_dir}`
export weighted_vht=0
cp /dev/null vht_bar_chart.dat
for dir in $dirs 
do
    case ${dir} in
    CLEAR_DRY) label="CD"
        ;;
    CLEAR_WET) label="CW"
        ;;
    RAIN_1) label="R1"
        ;;
    RAIN_2) label="R2"
        ;;
    RAIN_3) label="R3"
        ;;
    SNOW_1) label="S1"
        ;;
    SNOW_2) label="S2"
        ;;
    SNOW_3) label="S3"
        ;;
    SNOW_4) label="S4"
        ;;
    TEMP_1) label="T1"
        ;;
    TEMP_2) label="T2"
        ;;
    TEMP_3) label="T3"
        ;;
    VISIBILITY_1) label="V1"
        ;;
    VISIBILITY_2) label="V2"
        ;;
    VISIBILITY_3) label="V3"
        ;;
    WIND_1) label="W1"
        ;;
    WIND_2) label="W2"
        ;;
    WIND_3) label="W3"
        ;;
    *) echo not recognized type
    esac
    vht=`tail -n1 ${target_dir}/${dir}/moe_network.csv | cut -d',' -f18`
    echo ${label} ${vht} >> vht_bar_chart.dat
    tmp=`python weather_probability.py ${dir} ${vht} ${weighted_vht}`
    weighted_vht=${tmp}
done
echo WAVG ${weighted_vht} >> vht_bar_chart.dat

gnuplot vht_bar_chart.plt
